import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f5f5f5",
  },
  subContainer: {
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#B272A4",
    width: "100%",
    height: 380,
    position: "absolute",
    top: -270,
  },
  searchBarContainer: {
    position: "relative",
    // flex: 1,
    width: 360,
    height: 55,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 4,
    borderColor: "#FA89B8",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    top: 85,
    placeholder: {
      color: "lightgray",
      fontSize: 14,
    },
  },
  title: {
    fontFamily: "FiraSansBold",
    fontSize: 24,
    color: "#fff",
    marginTop: 285,
  },
  subtitle: {
    fontFamily: "FiraSansSemiBold",
    fontSize: 16,
    color: "#fff",
    marginBottom: 40,
  },
  content: {
    // justifyContent: "space-between",
    flexDirection: "column",
    position: "absolute",
    top: 155,
    paddingHorizontal: 18,
  },
  descriptionTitle: {
    fontFamily: "FiraSansMedium",
    fontSize: 22,
    color: "#B272A4",
  },
  description: {
    fontFamily: "FiraSansRegular",
    fontSize: 14,
    color: "#000",
    marginTop: 10,
  },
  catalogHeader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    bottom: 370,
    left: 5,
  },
  seeAllText: {
    fontFamily: "FiraSansMedium",
    fontSize: 18,
    color: "#FA89B8",
    marginLeft: 120,
  },
  cardContainer: {
    // flex: 1,
    // bottom: 80,
    // position: "absolute",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    shadowColor: "#171717",
    shadowOffset: { width: -5, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    width: 250,
    height: 160,
    padding: 8,
    marginVertical: 8,
    marginHorizontal: 10,
  },
  cardCover: {
    position: "absolute",
    left: -18,
    top: -2,
  },
  cardContent: {
    // flex: 1,
    // width: "80",
    justifyContent: "space-evenly",
    alignSelf: "center",
    paddingBottom: 5,
    left: 38,
    bottom: 5,
    marginLeft: 18,
    // marginBottom: 20,
  },
  nannyName: {
    fontFamily: "FiraSansMedium",
    fontSize: 16,
    color: "#000",
    alignSelf: "center",
  },
  nannyInformations: {
    fontFamily: "FiraSansRegular",
    fontSize: 12,
    color: "#9D9696",
    textAlign: "left",
  },
  viewProfileButton: {
    borderRadius: 20,
    width: "75%",
    height: 40,
    position: "absolute",
    alignSelf: "center",
    // top: 100,
  },
  viewProfileText: {
    fontFamily: "FiraSansSemiBold",
    fontSize: 15,
    textAlignVertical: "center",
  },
  testimonialsHeader: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    bottom: 120,
  },
  testimonialsTitle: {
    fontFamily: "FiraSansMedium",
    fontSize: 22,
    color: "#B272A4",
  },
  horizontalBar: {
    height: "50%",
    width: 3,
    backgroundColor: "#B272A4",
    marginRight: 5,
    borderRadius: 2,
  },
  testimonialContent: {
    fontFamily: "FiraSansRegular",
    fontSize: 13,
    color: "#000",
    textAlign: "center",
    marginBottom: 10,
  },
  testimonialAuthor: {
    fontFamily: "FiraSansMedium",
    fontSize: 14,
    color: "#FA89B8",
    alignSelf: "center",
    marginRight: 15,
  },
  testimonialClientType: {
    fontFamily: "FiraSansRegular",
    fontSize: 12,
    color: "#9D9696",
  },
  testimonialsCardContainer: {
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    shadowColor: "#171717",
    shadowOffset: { width: -5, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    width: 250,
    height: 230,
    padding: 8,
    marginVertical: 5,
    marginHorizontal: 10,
  },
  testimonialCardContent: {
    flex: 1,
    width: 240,
    height: 210,
    justifyContent: "center",
    alignItems: "center",
    top: 10,
    paddingBottom: 10,
  },
});

export default styles;
