import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f5f5f5",
  },
  subContainer: {
    alignItems: "center",
    justifyContent: "space-evenly",
    backgroundColor: "#B272A4",
    width: "100%",
    height: 110,
    position: "absolute",
  },
  searchBarContainer: {
    position: "relative",
    flex: 1,
    width: 360,
    height: 55,
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 4,
    borderColor: "#FA89B8",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    top: 85,
    placeholder: {
      color: "lightgray",
      fontSize: 14,
    },
  },
  title: {
    fontFamily: "FiraSansBold",
    fontSize: 24,
    color: "#fff",
  },
  subtitle: {
    fontFamily: "FiraSansSemiBold",
    fontSize: 16,
    color: "#fff",
    marginBottom: 20,
  },
  content: {
    justifyContent: "center",
    flexDirection: "column",
    position: "absolute",
    top: 155,
    paddingHorizontal: 18,
  },
  descriptionTitle: {
    fontFamily: "FiraSansMedium",
    fontSize: 22,
    color: "#B272A4",
  },
  description: {
    fontFamily: "FiraSansRegular",
    fontSize: 14,
    color: "#000",
  },
  catalogHeader: {
    flexDirection: "row",
    justifyContent: "center",
    position: "relative",
    bottom: 380,
  },
  seeAllText: {
    fontFamily: "FiraSansMedium",
    fontSize: 18,
    color: "#FA89B8",
    marginLeft: 140,
  },
  cardContainer: {
    // flex: 1,
    // bottom: 80,
    // position: "absolute",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    shadowColor: "#171717",
    shadowOffset: { width: -5, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    width: 250,
    height: 160,
    padding: 8,
    marginVertical: 8,
    marginHorizontal: 10,
  },
  cardCover: {
    position: "absolute",
    left: -18,
    top: -2,
  },
  cardContent: {
    flex: 1,
    // width: "80",
    justifyContent: "space-evenly",
    alignSelf: "center",
    paddingBottom: 5,
    left: 38,
    bottom: 5,
    marginLeft: 18,
    // marginBottom: 20,
  },
  nannyName: {
    fontFamily: "FiraSansMedium",
    fontSize: 16,
    color: "#000",
    alignSelf: "center",
  },
  nannyInformations: {
    fontFamily: "FiraSansRegular",
    fontSize: 12,
    color: "#9D9696",
    textAlign: "left",
  },
  viewProfileButton: {
    borderRadius: 20,
    width: "75%",
    height: 40,
    position: "absolute",
    alignSelf: "center",
    // top: 100,
  },
  viewProfileText: {
    fontFamily: "FiraSansSemiBold",
    fontSize: 15,
    textAlignVertical: "center",
  },
});

export default styles;
