export const allLocations = [
  { label: "Location", value: "location" },
  { label: "Agadir", value: "agadir" },
  { label: "Ain Aouda", value: "ain-aouda" },
  { label: "Al Hoceima", value: "al-hoceima" },
  { label: "Anza", value: "anza" },
  { label: "Asilah", value: "asilah" },
  { label: "Azilal", value: "azilal" },
  { label: "Azrou", value: "azrou" },
  { label: "Ben Ahmed", value: "ben-ahmed" },
  { label: "Ben Slimane", value: "ben-slimane" },
  { label: "Beni Mellal", value: "beni-mellal" },
  { label: "Bejaad", value: "bejaad" },
  { label: "Berrechid", value: "berrechid" },
  { label: "Berkane", value: "berkane" },
  { label: "Boujdour", value: "boujdour" },
  { label: "Bouznika", value: "bouznika" },
  { label: "Boudnib", value: "boudnib" },
  { label: "Chefchaouen", value: "chefchaouen" },
  { label: "Casablanca", value: "casablanca" },
  { label: "Dakhla", value: "dakhla" },
  { label: "Demnate", value: "demnate" },
  { label: "El Aaiún", value: "el-aaiun" },
  { label: "El Jadida", value: "el-jadida" },
  { label: "El Kelaa des Sraghna", value: "el-kelaa-des-sraghna" },
  { label: "Essaouira", value: "essaouira" },
  { label: "Errachidia", value: "errachidia" },
  { label: "Fes", value: "fes" },
  { label: "Figuig", value: "figuig" },
  { label: "Fquih Ben Salah", value: "fquih-ben-salah" },
  { label: "Guelmim", value: "guelmim" },
  { label: "Ifrane", value: "ifrane" },
  { label: "Inezgane", value: "inezgane" },
  { label: "Imilchil", value: "imilchil" },
  { label: "Imzouren", value: "imzouren" },
  { label: "Kelaa des Sraghna", value: "kelaa-des-sraghna" },
  { label: "Kenitra", value: "kenitra" },
  { label: "Khemisset", value: "khemisset" },
  { label: "Ksar el Kebir", value: "ksar-el-kebir" },
  { label: "Laayoune", value: "laayoune" },
  { label: "Larache", value: "larache" },
  { label: "Marrakech", value: "marrakech" },
  { label: "Merzouga", value: "merzouga" },
  { label: "Meknes", value: "meknes" },
  { label: "Midelt", value: "midelt" },
  { label: "Mohammedia", value: "mohammedia" },
  { label: "Moulay Driss Zerhoun", value: "moulay-driss-zerhoun" },
  { label: "Moulay Yacoub", value: "moulay-yacoub" },
  { label: "Nador", value: "nador" },
  { label: "Ouarzazate", value: "ouarzazate" },
  { label: "Oualidia", value: "oualidia" },
  { label: "Oued Laou", value: "oued-laou" },
  { label: "Oued Zem", value: "oued-zem" },
  { label: "Oujda", value: "oujda" },
  { label: "Ouazzane", value: "ouazzane" },
  { label: "Rabat", value: "rabat" },
  { label: "Safi", value: "safi" },
  { label: "Sale", value: "sale" },
  { label: "Sefrou", value: "sefrou" },
  { label: "Settat", value: "settat" },
  { label: "Sidi Bennour", value: "sidi-bennour" },
  { label: "Sidi Bouzid", value: "sidi-bouzid" },
  { label: "Sidi Ifni", value: "sidi-ifni" },
  { label: "Sidi Kacem", value: "sidi-kacem" },
  { label: "Sidi Taibi", value: "sidi-taibi" },
  { label: "Skhirate", value: "skhirate" },
  { label: "Smara", value: "smara" },
  { label: "Tafraout", value: "tafraout" },
  { label: "Taroudant", value: "taroudant" },
  { label: "Tarfaya", value: "tarfaya" },
  { label: "Taza", value: "taza" },
  { label: "Taourirt", value: "taourirt" },
  { label: "Temara", value: "temara" },
  { label: "Tinghir", value: "tinghir" },
  { label: "Tiznit", value: "tiznit" },
  { label: "Zagora", value: "zagora" },
];

export const allNationalities = [
  { label: "Nationality", value: "nationality" },
  { label: "Afghan", value: "afghan" },
  { label: "Albanian", value: "albanian" },
  { label: "Algerian", value: "algerian" },
  { label: "American", value: "american" },
  { label: "Andorran", value: "andorran" },
  { label: "Angolan", value: "angolan" },
  { label: "Argentinian", value: "argentinian" },
  { label: "Armenian", value: "armenian" },
  { label: "Australian", value: "australian" },
  { label: "Austrian", value: "austrian" },
  { label: "Azerbaijani", value: "azerbaijani" },
  { label: "Bahamian", value: "bahamian" },
  { label: "Bahraini", value: "bahraini" },
  { label: "Bangladeshi", value: "bangladeshi" },
  { label: "Barbadian", value: "barbadian" },
  { label: "Belarusian", value: "belarusian" },
  { label: "Belgian", value: "belgian" },
  { label: "Belizean", value: "belizean" },
  { label: "Beninese", value: "beninese" },
  { label: "Bhutanese", value: "bhutanese" },
  { label: "Bolivian", value: "bolivian" },
  { label: "Bosnian", value: "bosnian" },
  { label: "Botswanan", value: "botswanan" },
  { label: "Brazilian", value: "brazilian" },
  { label: "Bruneian", value: "bruneian" },
  { label: "Bulgarian", value: "bulgarian" },
  { label: "Burkinabe", value: "burkinabe" },
  { label: "Burmese", value: "burmese" },
  { label: "Burundian", value: "burundian" },
  { label: "Cabo Verdean", value: "cabo-verdean" },
  { label: "Cambodian", value: "cambodian" },
  { label: "Cameroonian", value: "cameroonian" },
  { label: "Canadian", value: "canadian" },
  { label: "Chadian", value: "chadian" },
  { label: "Chilean", value: "chilean" },
  { label: "Chinese", value: "chinese" },
  { label: "Colombian", value: "colombian" },
  { label: "Comorian", value: "comorian" },
  { label: "Congolese", value: "congolese" },
  { label: "Costa Rican", value: "costa-rican" },
  { label: "Croatian", value: "croatian" },
  { label: "Cuban", value: "cuban" },
  { label: "Cypriot", value: "cypriot" },
  { label: "Czech", value: "czech" },
  { label: "Danish", value: "danish" },
  { label: "Djiboutian", value: "djiboutian" },
  { label: "Dominican", value: "dominican" },
  { label: "Dutch", value: "dutch" },
  { label: "East Timorese", value: "east-timorese" },
  { label: "Ecuadorean", value: "ecuadorean" },
  { label: "Egyptian", value: "egyptian" },
  { label: "Emirati", value: "emirati" },
  { label: "Equatorial Guinean", value: "equatorial-guinean" },
  { label: "Eritrean", value: "eritrean" },
  { label: "Estonian", value: "estonian" },
  { label: "Eswatini", value: "eswatini" },
  { label: "Ethiopian", value: "ethiopian" },
  { label: "Fijian", value: "fijian" },
  { label: "Finnish", value: "finnish" },
  { label: "French", value: "french" },
  { label: "Gabonese", value: "gabonese" },
  { label: "Gambian", value: "gambian" },
  { label: "Georgian", value: "georgian" },
  { label: "German", value: "german" },
  { label: "Ghanaian", value: "ghanaian" },
  { label: "Greek", value: "greek" },
  { label: "Grenadian", value: "grenadian" },
  { label: "Guatemalan", value: "guatemalan" },
  { label: "Guinea-Bissauan", value: "guinea-bissauan" },
  { label: "Guinean", value: "guinean" },
  { label: "Guyanese", value: "guyanese" },
  { label: "Haitian", value: "haitian" },
  { label: "Honduran", value: "honduran" },
  { label: "Hungarian", value: "hungarian" },
  { label: "Icelandic", value: "icelandic" },
  { label: "Indian", value: "indian" },
  { label: "Indonesian", value: "indonesian" },
  { label: "Iranian", value: "iranian" },
  { label: "Iraqi", value: "iraqi" },
  { label: "Irish", value: "irish" },
  { label: "Israeli", value: "israeli" },
  { label: "Italian", value: "italian" },
  { label: "Ivoirian", value: "ivoirian" },
  { label: "Jamaican", value: "jamaican" },
  { label: "Japanese", value: "japanese" },
  { label: "Jordanian", value: "jordanian" },
  { label: "Kazakh", value: "kazakh" },
  { label: "Kenyan", value: "kenyan" },
  { label: "Kittitian and Nevisian", value: "kittitian-and-nevisian" },
  { label: "Kuwaiti", value: "kuwaiti" },
  { label: "Kyrgyz", value: "kyrgyz" },
  { label: "Laotian", value: "laotian" },
  { label: "Latvian", value: "latvian" },
  { label: "Lebanese", value: "lebanese" },
  { label: "Liberian", value: "liberian" },
  { label: "Libyan", value: "libyan" },
  { label: "Liechtenstein", value: "liechtenstein" },
  { label: "Lithuanian", value: "lithuanian" },
  { label: "Luxembourgish", value: "luxembourgish" },
  { label: "Malagasy", value: "malagasy" },
  { label: "Malawian", value: "malawian" },
  { label: "Malaysian", value: "malaysian" },
  { label: "Maldivian", value: "maldivian" },
  { label: "Malian", value: "malian" },
  { label: "Maltese", value: "maltese" },
  { label: "Marshallese", value: "marshallese" },
  { label: "Mauritanian", value: "mauritanian" },
  { label: "Mauritian", value: "mauritian" },
  { label: "Mexican", value: "mexican" },
  { label: "Micronesian", value: "micronesian" },
  { label: "Moldovan", value: "moldovan" },
  { label: "Monegasque", value: "monegasque" },
  { label: "Mongolian", value: "mongolian" },
  { label: "Montenegrin", value: "montenegrin" },
  { label: "Moroccan", value: "moroccan" },
  { label: "Mosotho", value: "mosotho" },
  { label: "Mozambican", value: "mozambican" },
  { label: "Namibian", value: "namibian" },
  { label: "Nauruan", value: "nauruan" },
  { label: "Nepalese", value: "nepalese" },
  { label: "New Zealander", value: "new-zealander" },
  { label: "Nicaraguan", value: "nicaraguan" },
  { label: "Nigerian", value: "nigerian" },
  { label: "Nigerien", value: "nigerien" },
  { label: "North Korean", value: "north-korean" },
  { label: "North Macedonian", value: "north-macedonian" },
  { label: "Norwegian", value: "norwegian" },
  { label: "Omani", value: "omani" },
  { label: "Pakistani", value: "pakistani" },
  { label: "Palauan", value: "palauan" },
  { label: "Palestinian", value: "palestinian" },
  { label: "Panamanian", value: "panamanian" },
  { label: "Papua New Guinean", value: "papua-new-guinean" },
  { label: "Paraguayan", value: "paraguayan" },
  { label: "Peruvian", value: "peruvian" },
  { label: "Polish", value: "polish" },
  { label: "Portuguese", value: "portuguese" },
  { label: "Qatari", value: "qatari" },
  { label: "Romanian", value: "romanian" },
  { label: "Russian", value: "russian" },
  { label: "Rwandan", value: "rwandan" },
  { label: "Samoan", value: "samoan" },
  { label: "San Marinese", value: "san-marinese" },
  { label: "Sao Tomean", value: "sao-tomean" },
  { label: "Saudi", value: "saudi" },
  { label: "Senegalese", value: "senegalese" },
  { label: "Serbian", value: "serbian" },
  { label: "Seychellois", value: "seychellois" },
  { label: "Sierra Leonean", value: "sierra-leonean" },
  { label: "Singaporean", value: "singaporean" },
  { label: "Slovak", value: "slovak" },
  { label: "Slovenian", value: "slovenian" },
  { label: "Solomon Islander", value: "solomon-islander" },
  { label: "Somali", value: "somali" },
  { label: "South African", value: "south-african" },
  { label: "South Korean", value: "south-korean" },
  { label: "South Sudanese", value: "south-sudanese" },
  { label: "Spanish", value: "spanish" },
  { label: "Sri Lankan", value: "sri-lankan" },
  { label: "Sudanese", value: "sudanese" },
  { label: "Surinamese", value: "surinamese" },
  { label: "Swazi", value: "swazi" },
  { label: "Swedish", value: "swedish" },
  { label: "Swiss", value: "swiss" },
  { label: "Syrian", value: "syrian" },
  { label: "Taiwanese", value: "taiwanese" },
  { label: "Tajik", value: "tajik" },
  { label: "Tanzanian", value: "tanzanian" },
  { label: "Thai", value: "thai" },
  { label: "Togolese", value: "togolese" },
  { label: "Tongan", value: "tongan" },
  { label: "Trinidadian and Tobagonian", value: "trinidadian-and-tobagonian" },
  { label: "Tunisian", value: "tunisian" },
  { label: "Turkish", value: "turkish" },
  { label: "Turkmen", value: "turkmen" },
  { label: "Tuvaluan", value: "tuvaluan" },
  { label: "Ugandan", value: "ugandan" },
  { label: "Ukrainian", value: "ukrainian" },
  { label: "Emirian", value: "emirian" },
  { label: "United Kingdom", value: "united-kingdom" },
  { label: "United States", value: "united-states" },
  { label: "Uruguayan", value: "uruguayan" },
  { label: "Uzbek", value: "uzbek" },
  { label: "Vanuatuan", value: "vanuatuan" },
  { label: "Venezuelan", value: "venezuelan" },
  { label: "Vietnamese", value: "vietnamese" },
  { label: "Yemeni", value: "yemeni" },
  { label: "Zambian", value: "zambian" },
  { label: "Zimbabwean", value: "zimbabwean" },
];

export const allPositions = [
  { label: "Position", value: "position" },
  { label: "Full-time", value: "full-time" },
  { label: "Part-time", value: "part-time" },
  { label: "Live-in", value: "live-in" },
  { label: "Live-out", value: "live-out" },
];
